force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/OrganizationName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationName__c</fullName>
    <label>Organization name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event Custom</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Venue Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Event End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zoom</fullName>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>Google Meet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <label>Recurring</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Do not repeat</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every Month</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Every Weekend</fullName>
            </value>
            <value>
                <fullName>Every Working Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Event Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Venue State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Venue Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pacific/Kiritimati</fullName>
            </value>
            <value>
                <fullName>Pacific/Chatham</fullName>
            </value>
            <value>
                <fullName>Pacific/Auckland</fullName>
            </value>
            <value>
                <fullName>Pacific/Enderbury</fullName>
            </value>
            <value>
                <fullName>Pacific/Fiji</fullName>
            </value>
            <value>
                <fullName>Pacific/Tongatapu</fullName>
            </value>
            <value>
                <fullName>Asia/Kamchatka</fullName>
            </value>
            <value>
                <fullName>Pacific/Norfolk</fullName>
            </value>
            <value>
                <fullName>Australia/Lord_Howe</fullName>
            </value>
            <value>
                <fullName>Australia/Sydney</fullName>
            </value>
            <value>
                <fullName>Pacific/Guadalcanal</fullName>
            </value>
            <value>
                <fullName>Australia/Adelaide</fullName>
            </value>
            <value>
                <fullName>Australia/Darwin</fullName>
            </value>
            <value>
                <fullName>Asia/Seoul</fullName>
            </value>
            <value>
                <fullName>Asia/Tokyo</fullName>
            </value>
            <value>
                <fullName>Asia/Hong_Kong</fullName>
            </value>
            <value>
                <fullName>Asia/Kuala_Lumpur</fullName>
            </value>
            <value>
                <fullName>Asia/Manila</fullName>
            </value>
            <value>
                <fullName>Asia/Shanghai</fullName>
            </value>
            <value>
                <fullName>Asia/Singapore</fullName>
            </value>
            <value>
                <fullName>Asia/Taipei</fullName>
            </value>
            <value>
                <fullName>Australia/Perth</fullName>
            </value>
            <value>
                <fullName>Asia/Bangkok</fullName>
            </value>
            <value>
                <fullName>Asia/Ho_Chi_Minh</fullName>
            </value>
            <value>
                <fullName>Asia/Jakarta</fullName>
            </value>
            <value>
                <fullName>Asia/Rangoon</fullName>
            </value>
            <value>
                <fullName>Asia/Dhaka</fullName>
            </value>
            <value>
                <fullName>Asia/Yekaterinburg</fullName>
            </value>
            <value>
                <fullName>Asia/Kathmandu</fullName>
            </value>
            <value>
                <fullName>Asia/Colombo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventRegistration/RouteEvent.cls
public without sharing class RouteEvent extends RestRoute {
	public override Object doGet() {
		Map<String, String> params = RestContext.request.params;
		String recordId = '';
		Object response;
		try {
			String sql = 'SELECT Id, Name, StartDate__c, StartTime__c, EndDate__c, EndTime__c, ' +
				'Description__c, Link__c, Provider__c, Recurring__c, Status__c, ' +
				'TimeZone__c, City__c, Country__c, PostalCode__c, State__c, Street__c, ( ' +
					'SELECT Id, LastName__c, FirstName__c, OrganizationName__c, Phone__c, Email__c FROM Attendees__r ' +
				') ' +
				'FROM Event__c';
			Integer pageSize = 100;
			String limitQuery = ' LIMIT ' + String.valueOf(pageSize);
			if (String.isNotBlank(params.get('pageSize'))) {
				pageSize = Integer.valueOf(EncodingUtil.urlEncode(params.get('pageSize'), 'UTF-8'));
				limitQuery = ' LIMIT ' + params.get('pageSize');
			}
			String offset = '';
			if (String.isNotBlank(params.get('pageNumber'))) {
				offset = ' OFFSET ' + ((Integer.valueOf(EncodingUtil.urlEncode(params.get('pageNumber'), 'UTF-8')) - 1) * pageSize);
			}
			String condition = '';
			if (String.isNotBlank(params.get('Id'))) {
				recordId = EncodingUtil.urlEncode(params.get('Id'), 'UTF-8');
				condition = ' Id = :recordId AND ';
			}
			if (String.isNotBlank(params.get('startDate'))) {
				Date startDate = Date.valueOf(EncodingUtil.urlEncode(params.get('startDate'), 'UTF-8'));
				condition = ' StartDate__c >= :startDate AND ';
			}
			if (String.isNotBlank(params.get('endDate'))) {
				Date endDate = Date.valueOf(EncodingUtil.urlEncode(params.get('endDate'), 'UTF-8'));
				condition = ' EndDate__c >= :endDate AND ';
			}
			if (String.isNotBlank(params.get('name'))) {
				String name = EncodingUtil.urlEncode(params.get('name'), 'UTF-8');
				condition = ' Name = :name AND ';
			}
			if (String.isNotBlank(params.get('provider'))) {
				String provider = EncodingUtil.urlEncode(params.get('provider'), 'UTF-8');
				condition = ' Provider__c = :provide AND ';
			}
			if (String.isNotBlank(params.get('status'))) {
				String status = EncodingUtil.urlEncode(params.get('status'), 'UTF-8');
				condition = ' Status__c = :status AND ';
			}
			condition = condition.removeEnd('AND ');
			condition = String.isNotBlank(condition) ? (' WHERE ' +  condition) : ' ';
			List<Event__c> events = Database.query(sql + condition +  limitQuery + offset);
			System.Debug('query=' + sql + condition +  limitQuery + offset);
			System.Debug('events=' + events.size());
			System.Debug('events=' + events);
			if (String.isNotBlank(recordId)) {
				if (!events.isEmpty()) {
					RestContext.response.statusCode = 200;
					response = events[0];
				} else {
					RestContext.response.statusCode = 404;
					List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
						new RestRouteError.RestException('Event does not exist', 'NOT_FOUND', 404)
					};
					response = errs;
				}
			} else {
				RestContext.response.statusCode = 200;
				response = events;
			}
		} catch(System.StringException ex){
			RestContext.response.statusCode = 400;
			List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
				new RestRouteError.RestException('Id is not a valid Id', 'BAD_REQUEST', 400)
			};
			response = errs;
		} catch (Exception ex) {
			RestContext.response.statusCode = 500;
			List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
				new RestRouteError.RestException(ex.getMessage(), 'BAD_REQUEST', 500)
			};
			response = errs;
		}
		return response;
    }
}