force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/OrganizationName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationName__c</fullName>
    <label>Organization name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/RegistrationStatus__c.field-meta.xml
<CustomField>
    <fullName>RegistrationStatus__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event Custom</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organaizer (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organaizer(Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Venue Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Event End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zoom</fullName>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>Google Meet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <label>Recurring</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Do not repeat</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every Month</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Every Weekend</fullName>
            </value>
            <value>
                <fullName>Every Working Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Event Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Venue State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Venue Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pacific/Kiritimati</fullName>
            </value>
            <value>
                <fullName>Pacific/Chatham</fullName>
            </value>
            <value>
                <fullName>Pacific/Auckland</fullName>
            </value>
            <value>
                <fullName>Pacific/Enderbury</fullName>
            </value>
            <value>
                <fullName>Pacific/Fiji</fullName>
            </value>
            <value>
                <fullName>Pacific/Tongatapu</fullName>
            </value>
            <value>
                <fullName>Asia/Kamchatka</fullName>
            </value>
            <value>
                <fullName>Pacific/Norfolk</fullName>
            </value>
            <value>
                <fullName>Australia/Lord_Howe</fullName>
            </value>
            <value>
                <fullName>Australia/Sydney</fullName>
            </value>
            <value>
                <fullName>Pacific/Guadalcanal</fullName>
            </value>
            <value>
                <fullName>Australia/Adelaide</fullName>
            </value>
            <value>
                <fullName>Australia/Darwin</fullName>
            </value>
            <value>
                <fullName>Asia/Seoul</fullName>
            </value>
            <value>
                <fullName>Asia/Tokyo</fullName>
            </value>
            <value>
                <fullName>Asia/Hong_Kong</fullName>
            </value>
            <value>
                <fullName>Asia/Kuala_Lumpur</fullName>
            </value>
            <value>
                <fullName>Asia/Manila</fullName>
            </value>
            <value>
                <fullName>Asia/Shanghai</fullName>
            </value>
            <value>
                <fullName>Asia/Singapore</fullName>
            </value>
            <value>
                <fullName>Asia/Taipei</fullName>
            </value>
            <value>
                <fullName>Australia/Perth</fullName>
            </value>
            <value>
                <fullName>Asia/Bangkok</fullName>
            </value>
            <value>
                <fullName>Asia/Ho_Chi_Minh</fullName>
            </value>
            <value>
                <fullName>Asia/Jakarta</fullName>
            </value>
            <value>
                <fullName>Asia/Rangoon</fullName>
            </value>
            <value>
                <fullName>Asia/Dhaka</fullName>
            </value>
            <value>
                <fullName>Asia/Yekaterinburg</fullName>
            </value>
            <value>
                <fullName>Asia/Kathmandu</fullName>
            </value>
            <value>
                <fullName>Asia/Colombo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventRegistration/RouteAttendee.cls
public without sharing class RouteAttendee extends RestRoute {
    public override Object doGet() {
		Map<String, String> params = RestContext.request.params;
		String recordId = '';
		Object response;
		try {
			if (String.isNotBlank(params.get('Id'))) {
				recordId = EncodingUtil.urlEncode(params.get('Id'), 'UTF-8');
			}
			List<Attendee__c> attendees = [
				SELECT Id, LastName__c, FirstName__c, OrganizationName__c, Phone__c, Event__c, Email__c,
					Event__r.Name, Event__r.StartDate__c, Event__r.StartTime__c, Event__r.EndDate__c, Event__r.EndTime__c,
					Event__r.Description__c, Event__r.Link__c, Event__r.Provider__c, Event__r.Recurring__c, Event__r.Status__c,
					Event__r.TimeZone__c, Event__r.City__c, Event__r.Country__c, Event__r.PostalCode__c, Event__r.State__c,
					Event__r.Street__c
				FROM Attendee__c
				WHERE Id = :recordId
			];
			if (!attendees.isEmpty()) {
				RestContext.response.statusCode = 200;
				response = attendees[0];
			} else {
				RestContext.response.statusCode = 404;
				List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
					new RestRouteError.RestException('Attendee does not exist', 'NOT_FOUND', 404)
				};
				response = errs;
			}
		} catch(System.StringException ex){
			RestContext.response.statusCode = 400;
			List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
				new RestRouteError.RestException('Id is not a valid Id', 'BAD_REQUEST', 400)
			};
			response = errs;
		} catch (Exception ex) {
			RestContext.response.statusCode = 500;
			List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
				new RestRouteError.RestException(ex.getMessage(), 'BAD_REQUEST', 500)
			};
			response = errs;
		}
		return response;
    }
	public override Object doPost() {
		RestRequest req = RestContext.request;
		Blob jsonBlob = req.requestBody;
		Object response;
    	String jsonString = jsonBlob.toString();
		Map<String, String> keyToField = new Map<String, String> {
			'accountId' => 'Account__c',
			'attendanceStatus' => 'AttendanceStatus__c',
			'contactId' => 'Contact__c',
			'email' => 'Email__c',
			'event' => 'Event__c',
			'firstName' => 'FirstName__c',
			'lastName' => 'LastName__c',
			'lead' => 'Lead__c',
			'organizationName' => 'OrganizationName__c',
			'phone' => 'Phone__c',
			'registrationStatus' => 'RegistrationStatus__c',
			'userId' => 'User__c',
			'id' => 'Id'
		};
		for (String key: keyToField.keySet()){
			String fieldName = '"' + keyToField.get(key) + '"';
			String regExp = '"' + key + '"';
			jsonString = jsonString.replaceAll(regExp, fieldName);
		}
		Attendee__c attendee = (Attendee__c)JSON.deserialize(jsonString, Attendee__c.class);
		Boolean isUpdate = false;
		if (String.isNotBlank(attendee.Id)) {
			isUpdate = true;
		}
		Database.UpsertResult[] upsertResults = Database.upsert(new List<Attendee__c> {attendee}, false);
		for (Integer i = 0; i < upsertResults.size(); i++) {
			Map<String, Object> clientResponse = new Map<String, Object>();
			if (!upsertResults[i].isSuccess()) {
				String errorMsg = '';
				for (Database.Error err : upsertResults[i].getErrors()) {
					errorMsg += err.getStatusCode() + ': ' + err.getMessage() + ' ';
				}
				RestContext.response.statusCode = 400;
				List<RestRouteError.RestException> errs = new List<RestRouteError.RestException>{ 
					new RestRouteError.RestException('Id is not a valid Id', 'BAD_REQUEST', 400)
				};
				response = errs;
			} else {
				RestContext.response.statusCode = isUpdate ? 200 : 201;
				response = attendee;
			}
		}
		return response;
	}
}