force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Custom</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event Custom</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organaizer(Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventRegistration/EventAPITest.cls
@IsTest
public with sharing class EventAPITest {
	@IsTest
	static void doGetTest() {
		Event__c event = new Event__c();
		event.Name = 'Zommer';
		insert event;
		Contact contactRecord = new Contact();
		contactRecord.LastName = 'Rock';
		contactRecord.FirstName = 'Simon';
		contactRecord.Email = 'simon@gmail.com';
		contactRecord.Phone = '+375336511245';
		insert contactRecord;
		Attendee__c attendee = new Attendee__c();
		attendee.Contact__c = contactRecord.Id;
		attendee.Event__c = event.Id;
		attendee.Email__c = 'zome@gmail.com';
		insert attendee;
		Attendee__c attendee1 = new Attendee__c();
		attendee1.Event__c = event.Id;
		attendee1.Email__c = 'kirov@gmail.com';
		insert attendee1;
		RestRouteTestUtil.setupRestContext('/services/apexrest/api/*', 'api/v1/events?Id=' + attendee.Id, new Map<String, String> {'Id' => event.Id});
		RestResponse resp = RestContext.Response;
		SObject  response;
		Test.startTest();
		RouteEvent routeEvent = new RouteEvent();
		response = (SObject)routeEvent.doGet();
		Test.stopTest();
		System.assertEquals(event.Name, response.get('Name'));
		System.assertEquals(2, response.getSObjects('Attendees__r').size());
	}
	@IsTest
	static void doGetNegativeTest() {
		Event__c event = new Event__c();
		event.Name = 'Zommer';
		insert event;

		Contact contactRecord = new Contact();
		contactRecord.LastName = 'Rock';
		contactRecord.FirstName = 'Simon';
		contactRecord.Email = 'simon@gmail.com';
		contactRecord.Phone = '+375336511245';
		insert contactRecord;
		Attendee__c attendee = new Attendee__c();
		attendee.Contact__c = contactRecord.Id;
		attendee.Event__c = event.Id;
		attendee.Email__c = 'zome@gmail.com';
		insert attendee;
		RestRouteTestUtil.setupRestContext('/services/apexrest/api/*', 'api/v1/attendees?Id=' + attendee.Id, new Map<String, String> {'Id' => '123'});
		RestResponse resp = RestContext.Response;
		List<RestRouteError.RestException> response;
		Test.startTest();
		RouteEvent routeEvent = new RouteEvent();
		response = (List<RestRouteError.RestException>)routeEvent.doGet();
		Test.stopTest();
		System.assertEquals(404, response[0].statusCode);
		System.assertEquals('Event does not exist', response[0].errorResp.message);
		System.assertEquals('NOT_FOUND', response[0].errorResp.errorCode);
	}
}