force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event Custom</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgSettings__c/OrgSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org settings</label>
</CustomObject>

force-app/main/default/objects/OrgSettings__c/fields/MaxNumberEventsPerUser__c.field-meta.xml
<CustomField>
    <fullName>MaxNumberEventsPerUser__c</fullName>
    <label>Maximum number of events per user</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test2/TriggerHandler_Event.cls
public with sharing class TriggerHandler_Event {
	public static void validateNumberCreatedEventsPerUser(List<Event__c> events) {
		date firstDayCurrentMonth = Date.today().toStartOfMonth();
		date firstDayNextMonth = firstDayCurrentMonth.addMonths(1);
		List<Event__c> createdEvents = [
			SELECT Id
			FROM Event__c 
			WHERE CreatedDate >= :firstDayCurrentMonth AND CreatedDate < :firstDayNextMonth AND CreatedById = :UserInfo.getUserId()
		];
		OrgSettings__c orgSettings = OrgSettings__c.getOrgDefaults();
		if (orgSettings.MaxNumberEventsPerUser__c != null) {
			Integer allowedSave = Integer.valueOf(orgSettings.MaxNumberEventsPerUser__c) - createdEvents.size();
			System.Debug(createdEvents.size() + ' ' + orgSettings.MaxNumberEventsPerUser__c);
			if (allowedSave < 0) {
				allowedSave = 0;
			}
			System.Debug('allowedSave=' + allowedSave);
			for (Integer i = allowedSave; i < events.size(); i++) {
				events[i].addError('Too many Events created this month for user ' + UserInfo.getUserName() + ' (' + UserInfo.getUserId()
					 + '): ' + orgSettings.MaxNumberEventsPerUser__c
				);
			}
		}
	}
}